### ISSUE TITLE
pip3 install -r requirements.txt

### ISSUE THREAD

**Issue by gearcapitan** [Chr0m0s0m3s/DeadTrapv2#1]
ERROR: Could not find a version that satisfies the requirement google=="3.0.0" (from -r requirements.txt (line 1)) (from versions: 1.9.3, 2.0.1, 2.0.2, 2.0.3, 3.0.0)
ERROR: No matching distribution found for google=="3.0.0" (from -r requirements.txt (line 1))

**Comment by gearcapitan** [comment]
Solution;


    /home/w/Do/T/DeadTrapv2  on   master !4    ✔ ▓▒░ cat requirements.txt
───────┬─────────────────────────────────────────────────────────────────────────────────────────────────────────────────────
       │ File: requirements.txt
───────┼─────────────────────────────────────────────────────────────────────────────────────────────────────────────────────
   1 ~ │ google==3.0.0
   2 ~ │ pyfiglet ==0.8.post1
   3 ~ │ Pillow ==7.2.0
   4 ~ │ bs4 ==0.0.1
   5 ~ │ argparse ==1.4.0
───────┴─────────────────────────────────────────────────────────────────────────────────────────────────────────────────────

**Comment by Chr0m0s0m3s** [comment]
thanks for the fix
