### ISSUE TITLE
Not running correctly

### ISSUE THREAD

**Issue by Getty-13** [Chr0m0s0m3s/DeadTrapv2#12]
When the file is run with the example syntax this is what is returned:
![image](https://user-images.githubusercontent.com/55208935/99894650-c5714100-2c7d-11eb-9403-46b11cb74423.png)

Please let me know what I am doing wrong so I can see what this tool has to offer.

**Comment by Chr0m0s0m3s** [comment]
you dont have the module requests installed so run `pip3 install requests` before running the tool

**Comment by Getty-13** [comment]
Thank you! I ran that command. but am still getting an error, as seen below. I appreciate the help btw!
![Screenshot_6](https://user-images.githubusercontent.com/55208935/99916105-05790800-2d00-11eb-9ffa-6ae3dc0d512e.png)

**Comment by Chr0m0s0m3s** [comment]
`pip3 install html5lib` anytime you see No module error or any library not installed just `pip3 install {library_name}`
