### ISSUE TITLE
requirement

### ISSUE THREAD

**Issue by aiobowheida** [Chr0m0s0m3s/DeadTrapv2#2]
ERROR: Could not find a version that satisfies the requirement google=="3.0.0" (from -r requirements.txt (line 1)) (from versions: 1.9.3, 2.0.1, 2.0.2, 2.0.3, 3.0.0)                                                            
ERROR: No matching distribution found for google=="3.0.0" (from -r requirements.txt (line 1))

**Comment by kenziy** [comment]
Same issue

**Comment by Chr0m0s0m3s** [comment]
Just remove ' " ' from the versions should solve the issue in the meantime I'm looking forward to update it

**Comment by Chr0m0s0m3s** [comment]
#1
