### ISSUE TITLE
some problems with import phonenumbers

### ISSUE THREAD

**Issue by MR-pentestGuy** [Chr0m0s0m3s/DeadTrapv2#8]
python3 main.go -h

Traceback (most recent call last):
File "main.py", line 4, in
from scanners.basicScan import libphonenumbers
ModuleNotFoundError: No module named 'phonenumbers'

python main.go -h

Traceback (most recent call last):
File "main.py", line 3, in
from scanners.fraud import *
ImportError: No module named scanners.fraud

**Comment by lilcsz** [comment]
pip3 install phonenumbers

**Comment by voronaam** [comment]
I created a PR fixing that in the requirements.txt
